export * as ResearchTool from "./research.js"
import { ToolFailure } from "@opencode/ai"
import type { Context } from "@opencode/plugin/effect/plugin"
import { Effect, Schema } from "effect"
import { KV } from "../../kv.js"
import { Permission } from "../../permission.js"
import { WebSearch } from "../../websearch.js"
const Cats = ["job","hotel","flight","product","youtube","place","event","course","service","other"] as const
const Category = Schema.Literals(Cats)
const Candidate = Schema.Struct({ id:Schema.String, category:Category, title:Schema.String, provider:Schema.optional(Schema.String), price:Schema.optional(Schema.Number), currency:Schema.optional(Schema.String), rating:Schema.optional(Schema.Number), reviewCount:Schema.optional(Schema.Number), location:Schema.optional(Schema.String), url:Schema.optional(Schema.String), summary:Schema.optional(Schema.String), details:Schema.optional(Schema.Json) })
const Search = Schema.Struct({ query:Schema.String.check(Schema.isMinLength(1),Schema.isMaxLength(500)), category:Category, location:Schema.optional(Schema.String), budget:Schema.optional(Schema.Number.check(Schema.isBetween({minimum:0,maximum:1000000000}))), maxResults:Schema.optional(Schema.Number.check(Schema.isBetween({minimum:1,maximum:50}))) })
const Classify = Schema.Struct({ query:Schema.String.check(Schema.isMinLength(1)), category:Category, candidates:Schema.Array(Candidate).check(Schema.isMinLength(1),Schema.isMaxLength(50)) })
const Shortlist = Schema.Struct({ operation:Schema.Literals(["list","save","remove","clear"] as const), candidate:Schema.optional(Candidate), id:Schema.optional(Schema.String) })
const Status = Schema.Struct({ provider:Schema.String, status:Schema.Literals(["configured","not_configured","unavailable","error"] as const), message:Schema.optional(Schema.String) })
const SearchOut = Schema.Struct({ query:Schema.String, category:Category, providers:Schema.Array(Status), candidates:Schema.Array(Candidate) })
const ClassifyOut = Schema.Struct({ engine:Schema.String, category:Category, recommendation:Schema.optional(Schema.String), rankings:Schema.Array(Schema.Struct({id:Schema.String,score:Schema.Number,confidence:Schema.Number,reasons:Schema.Array(Schema.String)})), tradeoffs:Schema.Array(Schema.String), warnings:Schema.Array(Schema.String) })
const ShortlistOut = Schema.Struct({ items:Schema.Array(Candidate) })
const StatusOut = Schema.Struct({ laya: Schema.Struct({ engine: Schema.Literals(["laya-mlx", "deterministic-fallback"]), available: Schema.Boolean, platform: Schema.String, arch: Schema.String }), providers: Schema.Array(Status) })
const prefix="research:shortlist:v1:"
const words=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g," ").trim().split(/\s+/).filter(Boolean)
const safe=(v:unknown)=>{if(typeof v!=="string")return;try{const u=new URL(v);return u.protocol==="https:"||u.protocol==="http:"?u.toString():undefined}catch{return}}
const rows=(v:unknown)=>Array.isArray(v)?v:v&&typeof v==="object"?(["candidates","results","jobs","items"] as const).map(k=>(v as Record<string,unknown>)[k]).find(Array.isArray)??[]:[]
const item=(v:unknown,category:typeof Category.Type):typeof Candidate.Type|undefined=>{if(!v||typeof v!=="object")return;const r=v as Record<string,unknown>;const title=typeof r.title==="string"?r.title:typeof r.name==="string"?r.name:"";if(!title)return;return {id:String(r.id??r.url??title),category,title:title.slice(0,300),provider:typeof r.provider==="string"?r.provider:undefined,price:typeof r.price==="number"?r.price:undefined,currency:typeof r.currency==="string"?r.currency:undefined,rating:typeof r.rating==="number"?r.rating:undefined,reviewCount:typeof r.reviewCount==="number"?r.reviewCount:undefined,location:typeof r.location==="string"?r.location:undefined,url:safe(r.url),summary:typeof r.summary==="string"?r.summary.slice(0,2000):undefined,details:r.details as never}}
const classify=(i:typeof Classify.Type)=>{const q=new Set(words(i.query));const ranked=i.candidates.map(c=>{const t=words(`${c.title} ${c.summary??""} ${c.location??""}`);let score=50;if(q.size)score+=Math.round([...q].filter(x=>t.some(y=>y.includes(x))).length/q.size*30);if(c.price!==undefined)score+=Math.max(-30,Math.min(20,20-c.price/100));if(c.rating!==undefined)score+=Math.max(-20,Math.min(20,c.rating*4));return {id:c.id,score:Math.max(0,Math.min(100,score)),confidence:Math.max(0,Math.min(1,.5+score/200)),reasons:[score>=70?"Matches the requested terms.":"Partially matches the requested terms.",c.price!==undefined?"Price is included for comparison.":"Price is unavailable.",c.rating!==undefined?"Rating is included for comparison.":"Rating is unavailable."]}}).sort((a,b)=>b.score-a.score);return {engine:"deterministic-fallback",category:i.category,recommendation:ranked[0]?.id,rankings:ranked,tradeoffs:["Ranking is explainable and deterministic until native Laya-MLX is available."],warnings:[]}}
const webResult = (value: WebSearch.Result, category: typeof Category.Type) => ({ id: value.url, category, title: value.title ?? value.url, provider: "web-search", url: value.url, summary: value.content?.slice(0, 2_000), details: value })
const req=(u:URL)=>Effect.tryPromise({try:()=>fetch(u,{headers:{accept:"application/json"},signal:AbortSignal.timeout(20000)}).then(async r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json() as unknown}),catch:e=>e}).pipe(Effect.mapError(e=>new ToolFailure({message:`Research provider failed: ${e instanceof Error?e.message:String(e)}`,error:e})))

const StatusInput = Schema.Struct({})
const statusProviders = () => ["job","hotel","flight","product","youtube","place","event","course","service"].map((id) => ({ provider: id, status: process.env[id === "job" ? "OPENCODE_JOBS_API_URL" : `OPENCODE_${id.toUpperCase()}_API_URL`] ? "configured" as const : "not_configured" as const, ...(id === "job" || process.env[`OPENCODE_${id.toUpperCase()}_API_URL`] ? {} : { message: "Provider is not configured." }) }))
const status = (): typeof StatusOut.Type => ({ laya: { engine: process.platform === "darwin" && process.arch === "arm64" ? "laya-mlx" : "deterministic-fallback", available: process.platform === "darwin" && process.arch === "arm64", platform: process.platform, arch: process.arch }, providers: statusProviders() })


export const Plugin = { id:"opencode.tool.research", effect:Effect.fn("ResearchTool.Plugin")(function*(ctx:Context){ const permission=yield*Permission.Service; const kv=yield*KV.Service; const websearch=yield* WebSearch.Service
  const guard=(action:string,resources:string[],c:any)=>permission.assert({action,resources,sessionID:c.sessionID,agent:c.agent,source:{type:"tool",messageID:c.messageID,id:c.id}}).pipe(Effect.mapError(e=>new ToolFailure({message:`Research permission denied: ${e.message}`,error:e})))
  yield* ctx.tool.transform(editor=>editor.add({name:"research_status",options:{codemode:false,permission:"research.status"},description:"Report Laya runtime and research provider availability without making external requests.",input:StatusInput,output:StatusOut,execute:(_i,c)=>Effect.gen(function*(){yield*guard("research.status",[c.sessionID],c);const output=status();return {output,content:JSON.stringify(output),metadata:{laya:output.laya.engine,providers:output.providers.length}}}) }))
  yield* ctx.tool.transform(editor=>editor.add({name:"research_search",options:{codemode:false,permission:"research.search"},description:"Search configured research providers. Never fabricates unavailable provider data.",input:Search,output:SearchOut,execute:(i,c)=>Effect.gen(function*(){yield*guard("research.search",[i.query],c);const env=i.category==="job"?"OPENCODE_JOBS_API_URL":`OPENCODE_${i.category.toUpperCase()}_API_URL`;const endpoint=process.env[env];if(!endpoint){const web=yield* websearch.query({query:`${i.category} ${i.query}`},{sessionID:c.sessionID}).pipe(Effect.mapError(e=>new ToolFailure({message:`Web research fallback unavailable: ${e instanceof Error?e.message:String(e)}`,error:e})));const webCandidates=web.results.map(x=>webResult(x,i.category)).slice(0,i.maxResults??20);const output={query:i.query,category:i.category,providers:[{provider:"web-search",status:"configured" as const,message:"Structured provider is not configured; results are web research candidates."}],candidates:webCandidates};return {output,content:JSON.stringify(output),metadata:{count:webCandidates.length,fallback:true}}};const u=new URL(endpoint);u.searchParams.set("q",i.query);if(i.location)u.searchParams.set("location",i.location);if(i.budget!==undefined)u.searchParams.set("budget",String(i.budget));u.searchParams.set("limit",String(i.maxResults??20));const raw=yield*req(u);const candidates=rows(raw).map(x=>item(x,i.category)).filter((x):x is typeof Candidate.Type=>!!x).slice(0,i.maxResults??20);const output={query:i.query,category:i.category,providers:[{provider:i.category,status:"configured" as const}],candidates};return {output,content:JSON.stringify(output),metadata:{count:candidates.length}}}) }))
  yield* ctx.tool.transform(editor=>editor.add({name:"research_classify",options:{codemode:false,permission:"research.classify"},description:"Rank research candidates with an explainable classifier.",input:Classify,output:ClassifyOut,execute:(i,c)=>Effect.gen(function*(){yield*guard("research.classify",[i.query],c);const output=classify(i);return {output,content:JSON.stringify(output),metadata:{count:output.rankings.length}}}) }))
  yield* ctx.tool.transform(editor=>editor.add({name:"research_shortlist",options:{codemode:false,permission:"research.shortlist"},description:"Persist a per-session research shortlist. It never books, purchases, applies, or contacts anyone.",input:Shortlist,output:ShortlistOut,execute:(i,c)=>Effect.gen(function*(){yield*guard("research.shortlist",[c.sessionID],c);const key=prefix+c.sessionID;const current=yield*kv.get(key);const items=Array.isArray(current)?current as typeof Candidate.Type[]:[];if(i.operation==="clear")yield*kv.set(key,[]);else if(i.operation==="remove"&&i.id)yield*kv.set(key,items.filter(x=>x.id!==i.id));else if(i.operation==="save"&&i.candidate)yield*kv.set(key,[...items.filter(x=>x.id!==i.candidate?.id),i.candidate]);const saved=yield*kv.get(key);const output={items:Array.isArray(saved)?saved as typeof Candidate.Type[]:[]};return {output,content:JSON.stringify(output),metadata:{count:output.items.length}}}) }))
}) }
export const __test={Search,Classify,Shortlist,classify,status,webResult}